<?php $this->jqueryUI(); $this->jvalidate(); $this->inlineScript()->CaptureStart();?>
var popup = <?php echo !empty($this->errorMessage) ? 'true' : 'false';?>;
$(document).ready(function(){
    $("#dialog").dialog({
        title: '發生下列錯誤',
        height: 200,
        modal: true,
        autoOpen: false
    });

    $('#form').validate({
        rules: {
            account: {
                required: true,
                email: true
            },
            password: 'required',
            'captcha[input]': 'required'
        },
        errorPlacement: function(error, element) {
           if (element.attr("name") == "captcha[input]") {
               error.insertAfter($(element).parent().children().last());
           } else {
               error.insertAfter(element);
           }
        }
    });

    if (popup) {
        $("#dialog").dialog('open');
    }
});
<?php $this->inlineScript()->CaptureEnd();?>
<form id="form" method="post" action="<?php echo $this->baseUrl('/auth/login/');?>">
<div id="login">
<h2>請輸入您的帳號管理</h2>
<hr>
<p class="clearfix"><label class="label" for="account">E-mail：</label><span><?php echo  $this->formText('account', $this->account);?></span></p>
<p class="clearfix"><label class="label" for="password">密碼：</label><span><?php echo $this->formPassword('password');?></span></p>
<p class="clearfix"><label class="label" for="captcha-input">驗證碼：</label><span><?php echo $this->formText('captcha[input]', '', array('class' => 'w80')) . $this->captcha->render() . $this->formHidden('captcha[id]', $this->captcha->getId()) ?></span></p>
<p class="clearfix"><label class="label">&nbsp;</label><span><input type="submit" class="btn" value="登入" /></span></p>
</div>
</form>
<div id="dialog">
    <ul>
<?php foreach ($this->errorMessage as $m) :?>
      <li><?php echo $m;?></li>
<?php endforeach;?>
    </ul>
</div>
