<?php echo $this->doctype() . PHP_EOL;?>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
<?php echo $this->headMeta() . PHP_EOL . $this->headTitle() . PHP_EOL . $this->headLink() . PHP_EOL;?>
<script src="<?php echo $this->baseUrl('/js/modernizr-2.0.6.min.js'); ?>"></script>
</head>
<body>
    <header>
        <nav>
            <div class="container_16">
                <h1 class="grid_16">Management</h1>
            </div>
        </nav>
    </header>
    <div id="middle">
        <div class="container_16">
            <?php echo $this->layout()->content . PHP_EOL; ?>
        </div>
    </div>
    <footer>
        <div class="container_16">

         </div>
    </footer>
<?php echo $this->headScript() . PHP_EOL . $this->inlineScript(); ?>
<!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
</body>
</html>