<!DOCTYPE html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]><html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]><html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en" class="no-js"><!--<![endif]-->
<head>
<?php echo $this->headMeta() . PHP_EOL . $this->headTitle() . PHP_EOL . $this->headLink() . PHP_EOL;?>
<script src="<?php echo $this->baseUrl('/js/modernizr-2.0.min.js'); ?>"></script>
</head>
<body>
    <div id="container">
        <header>
        </header>
        <div id="main" role="main">
    	<?php echo $this->layout()->content . PHP_EOL; ?>
        </div>
        <footer>
        </footer>
    </div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.js"></script>
<script>window.jQuery || document.write(unescape('%3Cscript src="<?php echo $this->baseUrl('/js/jquery-1.6.1.min.js'); ?>"%3E%3C/script%3E'));</script>
<?php echo $this->headScript() . PHP_EOL . $this->inlineScript(); ?>
<!--[if lt IE 7 ]>
<script src="<?php echo $this->baseUrl('/js/dd_belatedpng.js'); ?>"></script>
<script> DD_belatedPNG.fix('img, .png_bg');</script>
<![endif]-->
</body>
</html>