<!doctype html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]><html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]><html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en" class="no-js"><!--<![endif]-->
<head>
<?php echo $this->headMeta() . PHP_EOL . $this->headTitle() . PHP_EOL . $this->headLink() . PHP_EOL;?>
<script src="<?php echo $this->baseUrl('/js/modernizr-2.0.6.min.js'); ?>"></script>
</head>
<body>
    <header>
        <nav>
            <div class="container_16">

            </div>
        </nav>
    </header>
    <div id="middle">
        <div class="container_16">
            <?php echo $this->layout()->content . PHP_EOL; ?>
        </div>
    </div>
    <footer>
        <div class="container_16">

         </div>
    </footer>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('/js/jquery-1.7.0.min.js'); ?>"><\/script>');</script>
<?php echo $this->headScript() . PHP_EOL . $this->inlineScript(); ?>
</body>
</html>