<?php echo $this->doctype(); ?>
<html lang="en" class="no-js">
<head>
    <?php echo $this->headMeta(); ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/css/style.css'); ?>">
    <?php echo $this->headTitle(); ?>
    <script src="<?php echo $this->baseUrl('/js/head.min.js'); ?>"></script>
</head>
<body>
    <div id="container">
        <header>
        </header>
        <div id="main" role="main">
			<?php echo $this->layout()->content; ?>
        </div>
        <footer>
        </footer>
    </div>
    <script>
    head.js("https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js")
        .js("https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js");
    </script>

    <!--[if lt IE 7 ]>
    <script>
    head.js("<?php echo $this->baseUrl('/js/dd_belatedpng.js'); ?>", function(){
        DD_belatedPNG.fix('img, .png_bg');
    });
    </script>
    <![endif]-->
</body>
</html>